In [1]:
import numpy as np

In [2]:
# Tạo array 1 chiều
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [4]:
# Tạo array 2 chiều
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


In [8]:
# Tạo array với tất cả các phần tử 0
a1 = np.zeros((2,2))
print(a1)
a2 = np.zeros((5,2))
print(a2)

[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


In [10]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [16]:
# Tạo identity matrix kích thước 2*2
d1 = np.eye(2)
print(d1)

d2 = np.eye(5)
print(d2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
e = np.random.random((2,2))
print(e)

[[0.59019547 0.4466577 ]
 [0.93734048 0.6059356 ]]


In [17]:
# Tạo array 2 chiều với kích thước (3, 4)
# [[ 1 2 3 4]
# [ 5 6 7 8]
# [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [21]:
# slicing
print(a[:2, 1:3]) 
row_r1 = a[1, :] # output array 1 chieu shape (4,)
print(row_r1)
row_r2 = a[1:2, :] # output array 2 chieu shape (1, 4)
print(row_r2)

[[2 3]
 [6 7]]
[5 6 7 8]
[[5 6 7 8]]


In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [23]:
# Tinh tong
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [24]:
# Phep tru
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [29]:
# Nhan element-wise
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [27]:
# Chia element-wise
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
# Tinh can bac 2
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [30]:
v = np.array([9,10])
w = np.array([11, 12])

# Nhan vo huong
print(v.dot(w))
print(np.dot(v, w))

219
219


In [33]:
# Nhân ma trận
print((v.reshape(2,1)).dot(w.reshape(1,2)))
print(x.dot(y))
print(np.dot(x, y))

[[ 99 108]
 [110 120]]
[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [35]:
x = np.array([[1,2],[3,4]])
print(np.sum(x)) # Tính tổng tất cả phần tử trong array; prints "10"
print(np.sum(x, axis=0)) # Tính tổng phần tử mỗi hàng; prints "[4 6]"
print(np.sum(x, axis=1)) # Tính tổng phần tử mỗi cột; prints "[3 7]"

10
[4 6]
[3 7]


In [36]:
# Cộng vector v với mỗi hàng của ma trận x, kết quả lưu ở ma trận y.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Tạo 1 array có chiều giống x

# Dùng loop để vector v với mỗi hàng của ma trận
for i in range(4):
    y[i, :] = x[i, :] + v
# Kết quả của y
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
